// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "HowToUseAED",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "HowToUseAED",
            targets: ["AppModule"],
            bundleIdentifier: "xnoag.HowToUseAED",
            teamIdentifier: "47N48U5HD5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .heart),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeLeft,
                .landscapeRight,
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
